"""Markdown report assembly.

Three things are non-negotiable in every report this module produces:

* the comparison against buy and hold is the headline table, not an appendix;
* the caveats are appended automatically and cannot be switched off;
* the configuration hash and the data provenance are printed at the top, so any
  number in the document can be traced back to the exact inputs that made it.
"""

import datetime as _datetime
import os
from typing import Dict, List, Mapping, Optional, Sequence

import numpy as np
import pandas as pd

from .config import Config
from .metrics import currency_attribution, exit_reason_breakdown, yearly_returns

CAVEATS = """\
## Caveats -- read these before believing any number above

1. **A good-looking backtest is the null result, not the finding.** Trend
   following on mega-cap technology over the last fifteen years mostly measures
   the fact that mega-cap technology went up a great deal. The only question
   worth answering is whether these rules beat simply owning the index, after
   costs, after tax, and out of sample. That is why the buy-and-hold comparison
   is the first table in this document.
2. **Survivorship and hindsight bias in the universe.** The mega-cap list was
   assembled knowing which companies won. `configs/universe_2010.yaml` exists to
   measure the size of that bias: run the identical strategy on it and compare.
   If the 2010 universe does materially worse, the mega-cap result is largely
   stock-picking hindsight rather than strategy edge, and the honest expectation
   for live trading sits closer to the 2010 number.
3. **Taxes are not modelled at all.** German Abgeltungsteuer of 25 % plus
   Solidaritatszuschlag, and possibly church tax, falls on every realized gain,
   against a EUR 1,000 Sparerpauschbetrag. A high-turnover strategy pays that
   bill every year while buy and hold defers it indefinitely. An edge of two
   percentage points a year before tax can be a deficit after it.
4. **Currency risk is unhedged and material.** A euro account holding dollar
   stocks earns part of its return from the euro-dollar rate. The per-currency
   attribution table separates the two so a currency tailwind is not mistaken
   for skill.
5. **Stop fills are optimistic.** Daily bars cannot reproduce the intraday path.
   A gap through the stop is filled at the open here, which is conservative for
   gaps, but nothing in this model reproduces February 2018, March 2020, or a
   single-name earnings gap. Look at the cost stress test at two and four times
   the modelled friction before believing anything.
6. **Parameter selection contaminates the evaluation.** Walk-forward reduces
   this but cannot remove it: the *rules themselves* -- a twenty-day pullback
   inside a long uptrend, on technology stocks -- were chosen by a human who
   already knows how the last fifteen years went. No in-sample/out-of-sample
   split can measure that kind of overfitting.
7. **The sample is small.** A few hundred trades gives a large standard error on
   Sharpe and Calmar. Quote the bootstrap band, never the point estimate.
8. **Scope limits.** Long only, no leverage, no shorting, no options, no
   intraday data, a single-currency cash ledger, and no delisted or acquired
   companies in the universe.
9. **This is not financial advice.** And a backtest is not even past
   performance: it is a simulation of a decision rule that nobody actually
   followed.
"""

SYNTHETIC_WARNING = """\
> **These results come from synthetic data.** The prices were generated by a
> random process, not observed in a market. The run proves that the code
> executes and that the accounting balances. It says nothing whatsoever about
> whether the strategy makes money. For a real answer, fetch real prices with
> `python -m trendfolge.cli.download_data` and rerun.
"""

_PERCENT_METRICS = {
    "total_return",
    "cagr",
    "annual_volatility",
    "max_drawdown",
    "best_month",
    "worst_month",
    "positive_months",
    "hit_rate",
    "avg_win_pct",
    "avg_loss_pct",
    "avg_invested_fraction",
    "days_with_a_position",
}

HEADLINE_METRICS = [
    ("cagr", "CAGR"),
    ("total_return", "Total return"),
    ("annual_volatility", "Volatility"),
    ("sharpe", "Sharpe"),
    ("sortino", "Sortino"),
    ("max_drawdown", "Max drawdown"),
    ("max_drawdown_days", "Longest drawdown (days)"),
    ("calmar", "Calmar"),
    ("ulcer_index", "Ulcer index"),
    ("final_equity", "Final equity"),
]

TRADE_METRICS = [
    ("n_trades", "Trades"),
    ("hit_rate", "Hit rate"),
    ("avg_win_pct", "Average win"),
    ("avg_loss_pct", "Average loss"),
    ("payoff_ratio", "Payoff ratio"),
    ("profit_factor", "Profit factor"),
    ("expectancy_r", "Expectancy (R)"),
    ("avg_bars_held", "Average bars held"),
    ("max_consecutive_losses", "Worst losing streak"),
]

EXPOSURE_METRICS = [
    ("avg_invested_fraction", "Average invested"),
    ("days_with_a_position", "Days with a position"),
    ("avg_open_positions", "Average open positions"),
    ("max_open_positions", "Peak open positions"),
]

COST_METRICS = [
    ("annual_turnover", "Annual turnover"),
    ("total_commission", "Total commission"),
    ("total_slippage", "Total slippage and spread"),
    ("total_costs", "Total costs"),
    ("cost_drag_bps_per_year", "Cost drag (bps/year)"),
]


def format_value(key: str, value) -> str:
    """Render one metric value for a markdown table.

    Args:
        key: Metric name, which decides the formatting.
        value: The value.

    Returns:
        A short string. Missing values render as an em dash rather than as
        ``nan``, which reads as a bug.
    """
    if value is None:
        return "--"
    if isinstance(value, (pd.Timestamp, _datetime.date, _datetime.datetime)):
        return str(pd.Timestamp(value).date())
    if isinstance(value, (int, np.integer)):
        return f"{int(value):,}"
    if isinstance(value, (float, np.floating)):
        if not np.isfinite(value):
            return "inf" if value > 0 else "--"
        if key in _PERCENT_METRICS:
            return f"{value:.2%}"
        if abs(value) >= 1000:
            return f"{value:,.0f}"
        return f"{value:.2f}"
    return str(value)


def metrics_table(
    columns: Mapping[str, Mapping[str, object]], rows: Sequence
) -> str:
    """Build a markdown table comparing several runs across the same metrics.

    Args:
        columns: Ordered mapping of column heading to that run's metric dict.
        rows: Sequence of ``(metric_key, label)`` pairs.

    Returns:
        The markdown table.
    """
    headings = list(columns)
    lines = [
        "| Metric | " + " | ".join(headings) + " |",
        "|---" * (len(headings) + 1) + "|",
    ]
    for key, label in rows:
        cells = [format_value(key, columns[heading].get(key)) for heading in headings]
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def frame_to_markdown(frame: pd.DataFrame, float_format: str = "{:.3f}") -> str:
    """Render a DataFrame as a markdown table without extra dependencies."""
    if frame.empty:
        return "_(empty)_"
    display = frame.copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].map(
                lambda value: "--" if not np.isfinite(value) else float_format.format(value)
            )
        else:
            display[column] = display[column].astype(str)
    index_name = display.index.name or ""
    lines = [
        f"| {index_name} | " + " | ".join(str(column) for column in display.columns) + " |",
        "|---" * (len(display.columns) + 1) + "|",
    ]
    for label, row in display.iterrows():
        rendered = str(pd.Timestamp(label).date()) if isinstance(label, pd.Timestamp) else str(label)
        lines.append(f"| {rendered} | " + " | ".join(row.to_list()) + " |")
    return "\n".join(lines)


def header(
    title: str,
    config: Config,
    universe_name: str,
    account_currency: str,
    data_notes: Sequence[str],
    extra: Optional[Mapping[str, str]] = None,
) -> str:
    """Build the provenance header every report starts with."""
    lines = [
        f"# {title}",
        "",
        f"- Generated: {_datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"- Universe: `{universe_name}`",
        f"- Account currency: {account_currency}",
        f"- Configuration hash: `{config.hash}`",
        f"- Price mode: {config.data.price_mode}",
        f"- Regime filter: {config.strategy.regime_symbol} above its "
        f"{config.strategy.regime_sma}-day average",
    ]
    for key, value in (extra or {}).items():
        lines.append(f"- {key}: {value}")
    for note in data_notes:
        lines.append(f"- {note}")
    return "\n".join(lines)


def rules_section(config: Config) -> str:
    """Spell the traded rule set out in prose, at the parameters actually used."""
    strategy = config.strategy
    portfolio = config.portfolio
    return f"""\
## The rules that were traded

Signals are evaluated at the close of day T and executed at the open of the
symbol's next own session, which is what keeps the simulation free of
look-ahead.

**Entry**, all conditions on bar T:

1. {strategy.regime_symbol} closes above its {strategy.regime_sma}-day average
   (portfolio-level gate on new entries)
2. close above the {strategy.sma_long}-day average
3. the {strategy.sma_long}-day average above its own value
   {strategy.sma_slope_lookback} bars ago
4. the {strategy.sma_mid}-day average above the {strategy.sma_long}-day average
5. some low within the last {strategy.pullback_touch_window} bars reached the
   {strategy.sma_pullback}-day average
6. the lowest low in that window is no more than
   {strategy.pullback_max_depth_atr} ATRs below it -- a collapse is not a pullback
7. close back above the {strategy.sma_pullback}-day average, above the previous
   bar's high, and above its own open
8. price above {strategy.min_price_local} and 20-day traded value above
   {portfolio.account_currency} {strategy.min_adv_acct:,.0f}

**Exit**: an initial stop {strategy.atr_stop_mult} ATRs below the fill, a
Chandelier trailing stop {strategy.atr_trail_mult} ATRs below the highest close
since entry which ratchets upwards only, and a market exit when the close falls
below the {strategy.sma_long}-day average.

**Sizing**: {portfolio.risk_per_trade:.2%} of equity risked between entry and
initial stop, at most {portfolio.max_positions} positions, at most
{portfolio.max_position_weight:.0%} of equity per position,
{portfolio.max_portfolio_heat:.0%} total open risk, and at most
{portfolio.max_adv_participation:.0%} of a symbol's average volume per order.
"""


def build_backtest_report(
    result,
    metrics: Mapping[str, object],
    gross_metrics: Optional[Mapping[str, object]] = None,
    benchmark_metrics: Optional[Mapping[str, Mapping[str, object]]] = None,
    relative: Optional[Mapping[str, Mapping[str, float]]] = None,
    figures: Optional[Sequence[str]] = None,
    synthetic: bool = False,
) -> str:
    """Assemble the full markdown report of a single backtest.

    Args:
        result: The BacktestResult.
        metrics: Metrics of the net-of-cost run.
        gross_metrics: Metrics of the same run with the cost model zeroed.
        benchmark_metrics: Mapping of benchmark name to its metrics.
        relative: Mapping of benchmark name to the relative statistics.
        figures: Paths of figures to embed, relative to the report file.
        synthetic: Whether the prices were generated rather than observed.

    Returns:
        The markdown document.
    """
    sections: List[str] = [
        header(
            "Backtest report",
            result.config,
            result.universe_name,
            result.account_currency,
            result.data_notes,
            extra={
                "Period": f"{metrics.get('start')} to {metrics.get('end')}",
            },
        )
    ]
    if synthetic:
        sections.append(SYNTHETIC_WARNING)

    columns: Dict[str, Mapping[str, object]] = {"Strategy (net)": metrics}
    if gross_metrics is not None:
        columns["Strategy (gross)"] = gross_metrics
    for name, values in (benchmark_metrics or {}).items():
        columns[name] = values

    sections.append(
        "## Headline: does it beat simply owning the market?\n\n"
        + metrics_table(columns, HEADLINE_METRICS)
        + "\n\nThe gross column is the same run with every cost set to zero. The "
        "gap between it and the net column is the friction the strategy has to "
        "overcome before it earns anything."
    )

    if relative:
        rows = []
        for name, stats in relative.items():
            rows.append(
                f"| {name} | " + " | ".join(
                    format_value(key, stats.get(key))
                    for key in ("beta", "alpha_annual", "correlation", "up_capture",
                                "down_capture", "information_ratio")
                ) + " |"
            )
        sections.append(
            "### Relative to the benchmark\n\n"
            "| Benchmark | Beta | Alpha (annual) | Correlation | Up capture | "
            "Down capture | Information ratio |\n"
            + "|---" * 7 + "|\n"
            + "\n".join(rows)
        )

    sections.append(rules_section(result.config))

    sections.append(
        "## Trade statistics\n\n"
        + metrics_table({"Value": metrics}, TRADE_METRICS)
        + "\n\n### Exit reasons\n\n"
        + frame_to_markdown(exit_reason_breakdown(result.trades))
    )

    sections.append(
        "## Exposure\n\n" + metrics_table({"Value": metrics}, EXPOSURE_METRICS)
    )

    sections.append(
        "## Costs\n\n"
        + metrics_table({"Value": metrics}, COST_METRICS)
        + "\n\n"
        + _rejected_section(result)
    )

    attribution = currency_attribution(result.trades)
    sections.append(
        "## Where the profit came from, by currency\n\n"
        + frame_to_markdown(attribution)
        + "\n\nA large average FX return means a meaningful part of the result is "
        "the exchange rate rather than the stock selection."
    )

    sections.append(_yearly_section(result))
    sections.append(_extreme_trades_section(result))

    if figures:
        sections.append(
            "## Figures\n\n"
            + "\n\n".join(
                f"![{os.path.splitext(os.path.basename(path))[0].replace('_', ' ')}]"
                f"({os.path.basename(path)})"
                for path in figures
            )
        )

    sections.append(CAVEATS)
    return "\n\n".join(sections) + "\n"


def build_walkforward_report(
    result,
    config: Config,
    universe_name: str,
    account_currency: str,
    benchmark_metrics: Optional[Mapping[str, Mapping[str, object]]] = None,
    figures: Optional[Sequence[str]] = None,
    synthetic: bool = False,
) -> str:
    """Assemble the markdown report of a walk-forward run."""
    sections = [
        header(
            "Walk-forward report",
            config,
            universe_name,
            account_currency,
            [],
            extra={"Windows": str(len(result.windows))},
        ),
        "> The stitched out-of-sample curve below is **the** result. The "
        "in-sample columns are diagnostics: quoting them as performance would "
        "mean reporting how well the strategy fitted data it had already seen.",
    ]
    if synthetic:
        sections.append(SYNTHETIC_WARNING)

    columns: Dict[str, Mapping[str, object]] = {"Stitched out-of-sample": result.metrics}
    for name, values in (benchmark_metrics or {}).items():
        columns[name] = values
    sections.append(
        "## Out-of-sample result\n\n" + metrics_table(columns, HEADLINE_METRICS)
    )

    sections.append(
        "## Per-window detail\n\n"
        + frame_to_markdown(result.windows.set_index("test_start"))
    )

    stability = result.stability or {}
    sections.append(
        "## Parameter stability\n\n"
        + f"**{stability.get('verdict', 'unknown')}**\n\n"
        + f"- Distinct parameter sets chosen: {stability.get('distinct_sets', '--')} "
        f"across {stability.get('n_windows', '--')} windows\n"
        + f"- Most common set: `{stability.get('modal_parameters', {})}` "
        f"({format_value('share', stability.get('modal_share'))} of windows)\n"
        + f"- Windows that fell back to the defaults: "
        f"{stability.get('fallback_windows', '--')}\n\n"
        "A strategy whose best settings jump from year to year has found noise, "
        "not an effect."
    )

    sections.append(
        "## Trade statistics of the out-of-sample trades\n\n"
        + metrics_table({"Value": result.metrics}, TRADE_METRICS)
    )

    if figures:
        sections.append(
            "## Figures\n\n"
            + "\n\n".join(
                f"![{os.path.splitext(os.path.basename(path))[0].replace('_', ' ')}]"
                f"({os.path.basename(path)})"
                for path in figures
            )
        )

    sections.append(
        "### A note on the window handover\n\n"
        "A position still open when a window ends is marked out at the boundary "
        "without paying an exit cost, and the next window starts flat. Real "
        "trading would have carried it. This removes some trend continuation, "
        "which hurts the result, and skips an exit cost, which helps it; the net "
        "effect is small, but it is an artifact of the method rather than a "
        "property of the strategy."
    )

    sections.append(CAVEATS)
    return "\n\n".join(sections) + "\n"


def build_sensitivity_report(
    sweeps: pd.DataFrame,
    verdict: Mapping[str, object],
    cost_stress: pd.DataFrame,
    bootstrap_summary: Mapping[str, float],
    heatmap_matrix: Optional[pd.DataFrame],
    config: Config,
    universe_name: str,
    account_currency: str,
    figures: Optional[Sequence[str]] = None,
    synthetic: bool = False,
) -> str:
    """Assemble the markdown report of the robustness analysis."""
    sections = [
        header(
            "Robustness report", config, universe_name, account_currency, []
        )
    ]
    if synthetic:
        sections.append(SYNTHETIC_WARNING)

    sections.append(
        "## Verdict\n\n"
        + f"**{verdict.get('verdict', 'unknown')}**\n\n"
        + f"- Rule applied: {verdict.get('rule', '--')}\n"
        + f"- Share of the sampled neighbourhood holding up: "
        f"{format_value('share', verdict.get('share_holding_up'))}\n"
        + f"- Best Calmar found: {format_value('calmar', verdict.get('best_calmar'))}\n"
        + f"- Parameters that collapse over most of their range: "
        f"{verdict.get('fragile_parameters') or 'none'}\n\n"
        "The rule was fixed before the analysis was run, so it cannot be "
        "loosened now that the answer is known."
    )

    sections.append(
        "## One-factor-at-a-time sweeps\n\n"
        + frame_to_markdown(sweeps.set_index("parameter"))
    )

    if heatmap_matrix is not None and not heatmap_matrix.empty:
        sections.append(
            "## Stop against trail\n\n"
            + frame_to_markdown(heatmap_matrix)
            + "\n\nA broad plateau is robustness. A single bright cell surrounded "
            "by poor ones is curve fitting, and live trading lands in the "
            "surrounding cells."
        )

    sections.append(
        "## Cost stress\n\n"
        + frame_to_markdown(cost_stress.set_index("cost_factor"))
        + "\n\nIf the strategy dies at twice the modelled friction, it was never "
        "real: the true cost of trading is always worse than the model."
    )

    if bootstrap_summary:
        rows = "\n".join(
            f"| {key.replace('_', ' ')} | {value:,.3f} |"
            for key, value in bootstrap_summary.items()
        )
        sections.append(
            "## Bootstrap of the trade sequence\n\n"
            "| Statistic | Value |\n|---|---|\n" + rows + "\n\n"
            "Report the band, never the midpoint. With a few hundred trades the "
            "fifth and ninety-fifth percentiles are far apart, and that spread is "
            "the honest uncertainty around every other number in these reports."
        )

    if figures:
        sections.append(
            "## Figures\n\n"
            + "\n\n".join(
                f"![{os.path.splitext(os.path.basename(path))[0].replace('_', ' ')}]"
                f"({os.path.basename(path)})"
                for path in figures
            )
        )

    sections.append(CAVEATS)
    return "\n\n".join(sections) + "\n"


def write_report(text: str, path: str) -> str:
    """Write a report to disk, creating the directory if needed."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return path


def _rejected_section(result) -> str:
    """Summarize orders that could not be placed or filled in full."""
    if result.rejected.empty:
        return (
            "No order was rejected or truncated: every position the rules asked "
            "for could actually be taken."
        )
    counts = result.rejected["reason"].value_counts().to_frame("count")
    return (
        "### Orders that could not be filled as intended\n\n"
        + frame_to_markdown(counts)
        + "\n\nThese matter. A strategy whose results depend on positions the "
        "account could not actually afford is reporting a bug, not an edge."
    )


def _yearly_section(result) -> str:
    """Calendar year returns of the strategy."""
    returns = yearly_returns(result.equity["equity"])
    if returns.empty:
        return "## Calendar years\n\n_(the sample does not span a full year)_"
    frame = pd.DataFrame({"return": returns.to_numpy()},
                         index=[date.year for date in returns.index])
    frame.index.name = "year"
    return "## Calendar years\n\n" + frame_to_markdown(frame, "{:.2%}")


def _extreme_trades_section(result) -> str:
    """The ten best and ten worst trades."""
    if result.trades.empty:
        return "## Best and worst trades\n\n_(no trades)_"
    columns = ["symbol", "entry_date", "exit_date", "bars_held", "net_pnl_acct",
               "r_multiple", "exit_reason"]
    ordered = result.trades.sort_values("net_pnl_acct", ascending=False)
    best = ordered.head(10)[columns].reset_index(drop=True)
    worst = ordered.tail(10)[columns].reset_index(drop=True)
    return (
        "## Best and worst trades\n\n### Ten best\n\n"
        + frame_to_markdown(best, "{:.2f}")
        + "\n\n### Ten worst\n\n"
        + frame_to_markdown(worst, "{:.2f}")
    )
